package model

import "errors"

var (
	ErrConversationNotFound  = errors.New("conversation not found")
	ErrMessageNotFound       = errors.New("message not found")
	ErrUserNotInConversation = errors.New("user not in conversation")
	ErrPermissionDenied      = errors.New("permission denied")
	ErrInvalidMessageType    = errors.New("invalid message type")
	ErrCallAlreadyEnded      = errors.New("call already ended")
	ErrDeviceNotRegistered   = errors.New("device not registered")
	ErrUserAlreadyExists     = errors.New("user already exists")
	ErrUserNotFound          = errors.New("user not found")
	ErrEmailAlreadyExists    = errors.New("email already exists")
	ErrUsernameAlreadyExists = errors.New("username already exists")
	ErrUserBlocked           = errors.New("user blocked")
	ErrEmailNotVerified      = errors.New("email not verified")
	ErrEmailNotFound         = errors.New("email not found")
	ErrPasswordTooWeak       = errors.New("password too weak")
	ErrInvalidCredentials    = errors.New("invalid credentials")
	ErrTokenExpired          = errors.New("token expired")
	ErrTokenInvalid          = errors.New("token invalid")
	ErrTokenNotFound         = errors.New("token not found")
	ErrRefreshTokenExpired   = errors.New("refresh token expired")
	ErrRefreshTokenInvalid   = errors.New("refresh token invalid")
	ErrRefreshTokenNotFound  = errors.New("refresh token not found")
	ErrRateLimitExceeded     = errors.New("rate limit exceeded")
	ErrInternalServerError   = errors.New("internal server error")
	ErrServiceUnavailable    = errors.New("service unavailable")
	ErrInvalidInput          = errors.New("invalid input data")
	ErrDatabaseError         = errors.New("database error")
)
